# Patch to add OAuth port to frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: dashboard-proxy-tls
spec:
  ports:
  - port: 8443
    targetPort: dashboard-ui
    protocol: TCP
    name: dashboard-ui

